# Generated by Django 4.1.4 on 2023-02-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='Automationtimespend',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Botdesc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Botname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Botstatus',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Creationdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Developermail',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Kaizenawardstatus',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Mailnotes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Mailrecipient',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Mailsend',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Managermail',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Manualtimespend',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Process',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Requestormail',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Spocname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Startdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Subprocess',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Teamleadmail',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Technologyused',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Totaldaysaved',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Totaltimesaved',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Workstatus',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
