# Generated by Django 4.1.4 on 2023-02-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0002_alter_bot_automationtimespend_alter_bot_botdesc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botstatus', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Botstatus',
                'verbose_name_plural': 'Botstatus',
            },
        ),
        migrations.CreateModel(
            name='Kaizenstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kaizenstatus', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Kaizenstatus',
                'verbose_name_plural': 'Kaizenstatus',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processname', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Process',
            },
        ),
        migrations.CreateModel(
            name='Subprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subprocessname', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'SubProcess',
                'verbose_name_plural': 'SubProcess',
            },
        ),
        migrations.CreateModel(
            name='Workstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workstatus', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Workstatus',
                'verbose_name_plural': 'Workstatus',
            },
        ),
    ]
