# Generated by Django 4.1.4 on 2023-02-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0003_botstatus_kaizenstatus_process_subprocess_workstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaizenawardedyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kaizenawardedyear', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Kaizenawardedyear',
                'verbose_name_plural': 'Kaizenawardedyear',
            },
        ),
    ]
