# Generated by Django 4.1.4 on 2023-03-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0004_kaizenawardedyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='Kaizenawardyear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
