# Generated by Django 4.1.4 on 2023-03-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0005_alter_bot_kaizenawardyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='Kaizenawardyear',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
