# Generated by Django 4.1.7 on 2023-03-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0006_alter_bot_kaizenawardyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='Botstatus',
            field=models.CharField(blank=True, choices=[('Hold', 'Hold'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('User Acceptance Testing In Progress', 'User Acceptance Testing In Progress'), ('Development In Progress', 'Development In Progress')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Kaizenawardyear',
            field=models.CharField(blank=True, choices=[('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Process',
            field=models.CharField(blank=True, choices=[('AMG', 'AMG'), ('CPG', 'CPG'), ('ESG', 'ESG')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Subprocess',
            field=models.CharField(blank=True, choices=[('AMG', 'AMG'), ('CPG', 'CPG'), ('ESG', 'ESG')], max_length=250, null=True),
        ),
    ]
