# Generated by Django 4.1.4 on 2023-03-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0008_remove_bot_id_alter_bot_botno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='Process',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='Subprocess',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
