# Generated by Django 4.1.4 on 2023-04-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0010_alter_bot_botstatus_alter_bot_kaizenawardyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developermail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Developermail', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'DeveloperMail',
                'verbose_name_plural': 'DeveloperMail',
            },
        ),
    ]
