# Generated by Django 4.1.4 on 2023-04-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0011_developermail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailreport_cc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cc_address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Mailreport_to',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To_address', models.CharField(max_length=1000)),
            ],
        ),
    ]
