# Generated by Django 4.1.4 on 2023-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0012_mailreport_cc_mailreport_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailrecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailrecipient', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'MailRecipient',
                'verbose_name_plural': 'MailRecipient',
            },
        ),
        migrations.AlterModelOptions(
            name='mailreport_cc',
            options={'verbose_name': 'Mailreport_cc', 'verbose_name_plural': 'Mailreport_cc'},
        ),
        migrations.AlterModelOptions(
            name='mailreport_to',
            options={'verbose_name': 'Mailreport_to', 'verbose_name_plural': 'Mailreport_to'},
        ),
    ]
