# Generated by Django 4.1.4 on 2023-04-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0013_mailrecipient_alter_mailreport_cc_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbMailrecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbmailrecipient', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'MailRecipient',
                'verbose_name_plural': 'MailRecipient',
            },
        ),
        migrations.DeleteModel(
            name='Mailrecipient',
        ),
    ]
