# Generated by Django 4.1.4 on 2023-08-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0015_bot_enhanceenddate_bot_enhancestartdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='businessunit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
