# Generated by Django 4.1.4 on 2023-10-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0016_bot_businessunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='categorization',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='livestatus',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='priority',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
