# Generated by Django 4.1.4 on 2023-11-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0017_bot_categorization_bot_livestatus_bot_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
