# Generated by Django 4.1.4 on 2023-12-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0018_bot_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotHist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botno', models.IntegerField(blank=True)),
                ('botname', models.CharField(blank=True, max_length=250, null=True)),
                ('botstatus', models.CharField(blank=True, max_length=250, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('enhancestartdate', models.DateField(blank=True, null=True)),
                ('enhanceenddate', models.DateField(blank=True, null=True)),
                ('livestatus', models.CharField(blank=True, max_length=250, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_updated_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
