# Generated by Django 4.1.4 on 2023-12-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0020_bothist_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bothist',
            name='Developermail',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
