# Generated by Django 4.1.4 on 2023-12-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0021_bothist_developermail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bothist',
            options={'verbose_name': 'BotHistory', 'verbose_name_plural': 'BotHistory'},
        ),
        migrations.AlterField(
            model_name='bot',
            name='Botno',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bothist',
            name='botno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
