# Generated by Django 4.1.4 on 2023-12-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0022_alter_bothist_options_alter_bot_botno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='Botno_numeric',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
