# Generated by Django 4.1.4 on 2023-12-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botcreate', '0023_bot_botno_numeric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='Botno_numeric',
        ),
    ]
